### ISSUE TITLE
Colored icons to indicate article type

### ISSUE THREAD

**Issue by jamesvenning** [winkm89/teachPress#133]
In your example of making new types, you make them with different colours. Is it possible to make "Journal Article" one colour, "InProceedings" a different colour, etc.?

PS - really loving your plugin!

**Comment by winkm89** [comment]
Hi,
Sorry for the really late reply. :) Meanwhile it's possible to do this, because each one of the type badges has an own CSS selectors. So you can add rules for that to your WordPress theme, for example (red badge for journal articles):

```css
p.tp_pub_title .article {
    background-color: red !important;
}
```
