### ISSUE TITLE
How do I change the font color and reduce the box sizing to make the list of publications legible?

### ISSUE THREAD

**Issue by ktiwari9** [winkm89/teachPress#193]
Hi.

Thanks so much for the plugin. Being able to import bib entries at once made it easy to curate a list of publications for my website. I am currently preparing a publications but given my color palette, it's barely legible. Here is what I mean

![image](https://user-images.githubusercontent.com/5789469/154773396-1f1bdde5-9dd3-4e65-8a56-78e39573714d.png)

The selector boxes/dropdowns take up the whole screen width and I'd like to be able to reduce the size so they all fit in the same row.

Also the publication title font color should be something more like white etc. so I can see. How do I go about changing that? 

I am using Elementor Basic page builder with WordPress 5.9. Any thoughts/ suggestions?

**Comment by winkm89** [comment]
Hi,
Normally teachpress set only a color for labels (Inproceedings,..) and the menu line (BibTex. Tags)... The rest comes from your theme. So the title is for example the default link color. 

The good news is that every element has own CSS selectors. So you can give the elements the style you want. Here is a basic start, which should give you white font colors:

```css
.tp_pub_title, .tp_pub_additional, .tp_h3, .tp_pub_author {
color: #fff;
}

.tp_title_link {
color: #fff;
text-decoration: none;
}

.tp_title_link:hover {
color: #fff;
text-decoration: underline;
}
```

**Comment by ktiwari9** [comment]
Managed to fix the CSS per element by adding some "Additional Css" extending your example above.

![image](https://user-images.githubusercontent.com/5789469/154861232-77de8ff4-01ca-4c24-abe6-e42a766e4222.png)

I have 2 quick questions regarding the dropdown:

1.  How do I add some padding? They look like they are glued tight to each other.
2. Can there be dynamic spacing when someone expands the dropdown? For now, I have to add enough spacing manually so that even if the tab is expanded, it does not cover the publication listed below. See example below 
![image](https://user-images.githubusercontent.com/5789469/154861337-127557cb-ac78-477b-9a6e-e518930dfdc4.png)

**Comment by winkm89** [comment]
1. Margin between the filters:

```CSS
.teachpress_filter select {
    margin-right: 5px;
    margin-left: 5px;
}
```

2. I think that's not possible with plain CSS because you can't change the basic behavior of this drop-down lists (blend text and other elements). Maybe it's possible with JavaScript, but unfortunately I can't tell you exactly how.
