### ISSUE TITLE
location and size of Dimensions/PlumX badges

### ISSUE THREAD

**Issue by fkloosterman** [winkm89/teachPress#234]
Thanks for the nice plugin. After recent updates, my publication list created with tpcloud looks like as shown in the image below.

I use an image (the yellow sun) to highlight certain publications in the list. But now the Dimensions and PlumX badges draw most of the attention. Is it possible to change the size and location of the badges independently from the publication image? It would be nice to also independently control the links and the badges - I don't think both are necessary. By the way, there is no altmetric badge (it does work if I click the altmetric link) - is it supposed to show?

![image](https://github.com/winkm89/teachPress/assets/4592857/c4e910af-c5ae-4d67-b9d0-69223889e225)

**Comment by fabricebg** [comment]
It is possible to alter the appearance of the badges with CSS, among other solutions. To better help you, it would be interesting to get a link to your development site where the problem occurs.

**Comment by fkloosterman** [comment]
Hi,

Thanks for looking into this. Here is a link to the staging site: https://kloostermanlab.org/staging_site/publications/

I used the following command: `[tpcloud link_style="direct" show_altmetric_entry="1" show_plumx_widget="1" show_dimensions_badge="1" image="left" image_size="60" show_author_filter="0" show_type_filter="0" show_user_filter="0"]`

**Comment by fabricebg** [comment]
There are many solutions, but the quick and dirty one is to customize your theme Blocland FSE by adding to it the CSS rules at the bottom of my reply. You can follow this [tutorial](https://www.wpbeginner.com/plugins/how-to-easily-add-custom-css-to-your-wordpress-site/) if you need help doing this. It is only a matter of copy/pasting the CSS rules into your theme's custom CSS section.

@winkm89 : Possible future improvement: customize the embedded altmetric/dimension/plumx code.

```css
.__dimensions_badge_embed__ .__dimensions_Badge_style_medium_circle .__dimensions_Badge_Image {
	width: 60px !important;
	height: 60px !important;
}

.__dimensions_badge_embed__ .__dimensions_Badge_style_small_circle .__db_score, .__dimensions_badge_embed__ .__dimensions_Badge_style_medium_circle .__db_score, .__dimensions_badge_embed__ .__dimensions_Badge_style_large_circle .__db_score {
	font-size: 30px !important;
}

.PlumX-Popup .ppp-container.ppp-large > a, .PlumX-Popup .ppp-container.ppp-large .plx-print {
	width: 60px !important;
	height: 60px !important;
	margin-left: 0px !important;
}
```
